[2025-02-03T13:58:55.854+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-03T13:58:55.889+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: INETUM_ETL.preprocess_data manual__2025-02-03T13:58:38.091646+00:00 [queued]>
[2025-02-03T13:58:55.904+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: INETUM_ETL.preprocess_data manual__2025-02-03T13:58:38.091646+00:00 [queued]>
[2025-02-03T13:58:55.906+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-03T13:58:55.968+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-02-03 13:58:38.091646+00:00
[2025-02-03T13:58:55.979+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=122) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-03T13:58:55.982+0000] {standard_task_runner.py:63} INFO - Started process 124 to run task
[2025-02-03T13:58:55.982+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'INETUM_ETL', 'preprocess_data', 'manual__2025-02-03T13:58:38.091646+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/dagto_csv.py', '--cfg-path', '/tmp/tmpmekpgfkm']
[2025-02-03T13:58:55.984+0000] {standard_task_runner.py:91} INFO - Job 268: Subtask preprocess_data
[2025-02-03T13:58:56.111+0000] {task_command.py:426} INFO - Running <TaskInstance: INETUM_ETL.preprocess_data manual__2025-02-03T13:58:38.091646+00:00 [running]> on host 2892ee60bb8a
[2025-02-03T13:58:56.342+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='INETUM_ETL' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T13:58:38.091646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-03T13:58:38.091646+00:00'
[2025-02-03T13:58:56.344+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-03T13:58:56.431+0000] {dagto_csv.py:66} INFO - Proceso de preprocess_data realizado con exito, se extrajeron 500 registros unicos
[2025-02-03T13:58:56.432+0000] {dagto_csv.py:67} INFO - El archivo temporal se guardo en la ruta /tmp/df.json
[2025-02-03T13:58:56.433+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-03T13:58:56.434+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-03T13:58:56.450+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=INETUM_ETL, task_id=preprocess_data, execution_date=20250203T135838, start_date=20250203T135855, end_date=20250203T135856
[2025-02-03T13:58:56.520+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-03T13:58:56.574+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-03T13:58:56.612+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
